language: cpp
os: linux
compiler: gcc
env: CONFIG=Release
group: stable
dist: trusty

install:
    - sudo apt-add-repository -y ppa:beineri/opt-qt532-trusty
    - sudo apt-get -qq update
    - sudo apt-get install qt53tools
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
    
script:
    - QTDIR="/opt/qt53"
    - PATH="$QTDIR/bin:$PATH"
    - qt53-env.sh
    - qmake -v
    - ./configure.py --qmake-bin $(which qmake)
    - make
    - ./configure.py --back-end --debug --test --qmake-bin $(which qmake)
    - make
    - ./scripts/tool.sh --run-tests
    - ./scripts/tool.sh --run-func-tests --debug

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            
        packages:
            - zlib1g-dev
            - g++-5
